bugs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # pages
    path('', views.homePage, name="home"),
    path('about/', views.aboutPage, name="about"),
    path('tickets/', views.ticketsPage, name="tickets"),
    path('dashboard/', views.dashboardPage, name="dashboard"),
    path('login/', views.loginPage, name="login"),
    path('register/', views.registerPage, name="register"),
    path('createTicket/', views.createTicketPage),
    path('deleteTicket/', views.deleteTicketPage),
    path('createUpdate/', views.createUpdatePage),
    path('tickets/', views.ticketsPage),
    path('ticket/details/<str:id>', views.ticketDetailsPage),
    path('update/details/<str:id>', views.updateDetailsPage),
    path('profile/<str:id>', views.profilePage),
    # backend
    path('submit_ticket/', views.submit_ticket),
    path('submit_update/', views.submit_update),
    path('login_user/', views.login_user),
    path('logout_user/', views.logout_user, name='logout'),
    path('register_user/', views.register_user, name='register_user'),
    path('ticket/update/<str:id>', views.update_ticket),
    path('ticket/delete/<str:id>', views.delete_ticket),
    path('update/delete/<str:id>', views.delete_update),
    path('search_tickets/', views.search_tickets),
    path('search_categories/', views.search_categories1),
    path('search_categories/<str:q>', views.search_categories2),
]

bugtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bugs.urls')),
]

bugs/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    userId = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=50, null=True)
    lastName = models.CharField(max_length=75, null=True)
    username = models.CharField(max_length=50, null=True)
    department = models.CharField(max_length=20, null=True)
    position = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.username

class Ticket(models.Model):
    STATUS = (
        ('Created', 'Created'),
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
        ('Void', 'Void'),
    )

    URGENCY = (
        ('Green', 'Green'),
        ('Yellow', 'Yellow'),
        ('Red', 'Red'),
    )

    ticketId = models.AutoField(primary_key=True)
    title = models.CharField(max_length=80, null=True)
    description = models.CharField(max_length=255, null=True)
    status = models.CharField(max_length=100, null=True, choices=STATUS)
    category = models.CharField(max_length=20, null=True)
    urgency = models.CharField(max_length=50, null=True, choices=URGENCY)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    createdBy = models.ForeignKey(Employee, null=True, on_delete=models.SET_NULL, related_name='createdBy')
    assignedTo = models.ForeignKey(Employee, null=True, on_delete=models.SET_NULL, related_name='assignedTo')

    def __str__(self):
        return self.title

class Update(models.Model):
    updateId = models.AutoField(primary_key=True)
    description = models.CharField(max_length=255)
    madeBy = models.ForeignKey(Employee, null=True, on_delete=models.SET_NULL)
    onTicket = models.ForeignKey(Ticket, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.description

bugs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Ticket, Update

#Antonio: form to register a new user into the system.
class TicketForm(ModelForm):
	class Meta:
		model = Ticket
		fields = '__all__'

	def __init__(self,*args,**kwargs):
		super(TicketForm,self).__init__(*args,**kwargs)

		self.fields['title'].widget.attrs['class'] = 'form-control'
		self.fields['description'].widget = forms.Textarea()
		self.fields['description'].widget.attrs['class'] = 'form-control'
		self.fields['description'].required = False
		self.fields['status'].widget.attrs['class'] = 'custom-select'
		self.fields['category'].widget.attrs['class'] = 'form-control'
		self.fields['urgency'].widget.attrs['class'] = 'custom-select'
		self.fields['createdBy'].widget.attrs['class'] = 'custom-select'
		self.fields['createdBy'].label = 'Created By'
		self.fields['assignedTo'].widget.attrs['class'] = 'custom-select'
		self.fields['assignedTo'].label = 'Assigned To'

class UpdateForm(ModelForm):
    class Meta:
        model = Update
        fields = '__all__'

class LoginUserForm(forms.Form):
	username = forms.CharField(max_length=40, widget=forms.TextInput(attrs = {'class':'form-control'}))
	password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs = {'class':'form-control'}))

class RegisterUserForm(UserCreationForm):
	email = forms.EmailField(widget = forms.EmailInput(attrs = {'class':'form-control'}))
	first_name = forms.CharField(required=False, max_length=40, widget = forms.TextInput(attrs = {'class':'form-control'}))
	last_name = forms.CharField(required=False, max_length=40, widget = forms.TextInput(attrs = {'class':'form-control'}))
	address = forms.CharField(required=False, max_length=150, widget = forms.TextInput(attrs = {'class':'form-control'}))
	position = forms.CharField(required=False, max_length=50, widget = forms.TextInput(attrs = {'class':'form-control'}))
	department = forms.CharField(required=False, max_length=50, widget = forms.TextInput(attrs = {'class':'form-control'}))
	company = forms.CharField(required=False, max_length=50, widget = forms.TextInput(attrs = {'class':'form-control'}))
	class Meta:
		model = User
		fields = ('username','first_name','last_name','email','password1','password2','address','company','position','department')

	def __init__(self,*args,**kwargs):
		super(RegisterUserForm,self).__init__(*args,**kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['class'] = 'form-control'

bugs/views.py
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import *
from .forms import *

def valuesListToList(vl):
    return [item for t in vl for item in t]

# Andrew
def homePage(request):
    context = {"updates": Update.objects.all()}
    context["logged_in"] = request.user.is_authenticated
    if request.user.is_authenticated:
        context["totalTicketsCount"] = Ticket.objects.all().filter(Q(status='Created') | Q(status='In Progress')).count()
        context["pendingTicketsCount"] = Ticket.objects.all().filter(status='Created').count()
        context["inprogressTicketsCount"] = Ticket.objects.all().filter(status='In Progress').count()
        context["createTickets"] = searchTickets(request, createUser=request.user.username)
        context["assignTickets"] = searchTickets(request, assignUser=request.user.username)
        return render(request, 'bugs/dashboard.html', context)
    else:
        return render(request, 'bugs/landing.html')

#Antonio: defines the views and provides user login authenication for the system
@login_required(login_url="/login")
def dashboardPage(request):
    return homePage(request)

@login_required(login_url="/login")
def ticketsPage(request):
    context = {"tickets": searchTickets(request)}
    context["totalTicketsCount"] = Ticket.objects.all().filter(Q(status='Created') | Q(status='In Progress')).count()
    context["pendingTicketsCount"] = Ticket.objects.all().filter(status='Created').count()
    context["inprogressTicketsCount"] = Ticket.objects.all().filter(status='In Progress').count()
    context["createTickets"] = searchTickets(request, createUser=request.user.username)
    context["query"] = request.GET
    return render(request, 'bugs/tickets.html', context)

def aboutPage(request):
    return render(request, 'bugs/about.html')

def ticketDetailsPage(request, id):
    id1 = int(id)
    context = {"ticket": searchTickets(request, id=id1)[0]}
    context["users"] = valuesListToList(Employee.objects.values_list("username"))
    return render(request,'bugs/ticket_details.html',context)

def updateDetailsPage(request, id):
    id1 = int(id)
    context = {"update": Update.objects.filter(updateId__exact=id1)[0]}
    context["ticket"] = context["update"]
    context["users"] = valuesListToList(Employee.objects.values_list("username"))
    return render(request,'bugs/update_details.html',context)

# LOGIN
def loginPage(request):
    return render(request, 'bugs/login.html', context={"form": LoginUserForm()})

def registerPage(request):
    return render(request, 'authenticate/register.html', context={"form": RegisterUserForm()})

@login_required(login_url="/login")
def profilePage(request, id):
    res = Employee.objects.all().filter(username=id)[0]
    res.is_authenticated = True
    return render(request, 'bugs/profile.html', {'user': res})

# TICKETS
@login_required(login_url="/login")
def createTicketPage(request):
    return render(request,'bugs/create_ticket.html', context={"form": TicketForm()})

@login_required(login_url="/login")
def updateTicketPage(request):
    return render(request,'bugs/update_ticket.html')

@login_required(login_url="/login")
def deleteTicketPage(request):
    return render(request,'bugs/delete_ticket.html')

# UPDATES
@login_required(login_url="/login")
def createUpdatePage(request):
    return render(request,'bugs/create_update.html', context={"form": UpdateForm()})

def submit_update(request):
    if request.method == "GET":
        form = UpdateForm(request.GET)
        if form.is_valid():
            form.save()
            # title = form.cleaned_data['title']
            # category = form.cleaned_data['category']
            # urgency = form.cleaned_data['urgency']
            messages.success(request, ("Update submitted"))
    return redirect('dashboard')

def delete_update(request, id):
    id1 = int(id)
    t = Update.objects.filter(id=id1)[0]
    if t is not None:
        t.delete()
    return redirect('dashboard')

# USERS
def login_user(request):
   if request.method == "GET":
        form = LoginUserForm(request.GET)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
            else:
                messages.success(request, ("Error logging in. Try again."))
                return redirect('login')
        else:
            messages.success(request, ("Error logging in. Try again."))
            return redirect('login')
   else:
	    return render(request,'login.html')

def logout_user(request):
    logout(request)
    messages.success(request, ("Logged out."))
    return redirect('home')

def register_user(request):
  if request.method == "GET":
    form = RegisterUserForm(request.GET)
    if form.is_valid():
        firstName = form.cleaned_data["first_name"]
        lastName = form.cleaned_data["last_name"]
        position = form.cleaned_data["position"]
        department = form.cleaned_data["department"]
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']

        employee = Employee.objects.create(firstName=firstName, lastName=lastName, username=username, position=position, department=department)
        employee.save()

        form.save()

        user = authenticate(username=username, password=password)
        login(request, user)

        messages.success(request, ("Your registration is complete!"))
        return redirect('dashboard')
  else:
        form = RegisterUser()
  return render(request,'authenticate/register.html',{'form':form})

# TICKETS
def searchTickets(request, id=-1, title="", category="", urgency="", createDate="", createUser="", assignUser=""):
    res = Ticket.objects.all()
    if id > -1:
        res = res.filter(ticketId__exact=id)
    if len(title) > 0:
        res = res.filter(title__icontains=title)
    if len(category) > 0:
        res = res.filter(category__iexact=category)
    if len(urgency) > 0:
        res = res.filter(urgency__iexact=urgency)
    if len(createDate) > 0:
        res = res.filter(timestamp__iexact=createDate)
    if len(createUser) > 0:
        createUsernames = Employee.objects.filter(username__exact=createUser)
        createUser1 = -1
        if len(createUsernames) > 0:
            createUser1 = createUsernames[0].userId
        if createUser1 > -1:
            res = res.filter(createdBy_id__exact=createUser1)
    if len(assignUser) > 0:
        assignUsernames = Employee.objects.filter(username__exact=assignUser)
        assignUser1 = -1
        if len(assignUsernames) > 0:
            assignUser1 = assignUsernames[0].userId
        if assignUser1 > -1:
            res = res.filter(assignedTo_id__exact=assignUser1)
    return res

def update_ticket(request, id):
    if request.method == "GET":
        t = Ticket.objects.filter(ticketId__exact=id)[0]
        t.title = request.GET["title"]
        t.description = request.GET["description"]
        t.status = request.GET["status"]
        t.urgency = request.GET["urgency"]
        t.assignedTo = Employee.objects.filter(username__exact=request.GET["assignedTo"])[0]
        t.save()
        messages.success(request, ("Ticket updated"))
    return redirect('tickets')

def submit_ticket(request):
    if request.method == "GET":
        # form = CreateTicketForm(request.GET)
        form = TicketForm(request.GET)
        if form.is_valid():
            form.save()
            # title = form.cleaned_data['title']
            # category = form.cleaned_data['category']
            # urgency = form.cleaned_data['urgency']
            messages.success(request, ("Ticket submitted"))
    return redirect('dashboard')

def delete_ticket(request, id):
    id1 = int(id)
    t = searchTickets(request, id=id1)[0]
    if t is not None:
        t.delete()
    return redirect('tickets')

def search_tickets(request):
    if request.method == "GET":
        id = int(request.GET["id"]) if len(request.GET["id"]) > 0 else -1
        title = request.GET["title"]
        context = {"tickets": searchTickets(request, id=id, title=title)}
        context["totalTicketsCount"] = Ticket.objects.all().filter(Q(status='Created') | Q(status='In Progress')).count()
        context["pendingTicketsCount"] = Ticket.objects.all().filter(status='Created').count()
        context["inprogressTicketsCount"] = Ticket.objects.all().filter(status='In Progress').count()
        context["createTickets"] = searchTickets(request, createUser=request.user.username)
        context["query"] = request.GET
        return render(request,'bugs/tickets.html',context)
    return render(request,'bugs/tickets.html')

def search_categories1(request):
    return HttpResponse()

def search_categories2(request, q):
    txt = ""
    if request.method == "GET":
        lt = Ticket.objects.values_list("category")
        l = valuesListToList(lt)
        if len(q) > 0:
            for i in l:
                if q.lower() not in i.lower():
                    l.remove(i)
        s = set(l)
        txt = str(s)
        txt = txt[1:-1].replace("'", "")
    return HttpResponse(txt)

bugs/templates/bugs/about.html
{% extends 'bugs/base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br />
<br />
<br />
<br />
<style>
  .about p {
    color: white;
    text-align: center;
  }
</style>

<div1 class="about">
  <h1>About BugTracker</h1>
  <p>
    Bug tracker allows you to record bugs and other issues within your projects. Now your team of engineers have a fun
    and easy tool to use for your engineering projects and endeavors! Bug Tracker is easy to use simply follow the following steps
    1. In the dashboard you have an overall of all the tickets for your project. An overall of all the tickets assigned to you and their attributes are
    shown to let you know which tickets need work, when it was created, and the urgency to fix. To create your own ticket, simple click <q>
      Create ticket
    </q> and you will be taken to the create ticket page to input your ticket. Here in the create ticket page, enter a title and category for
    your ticket and describe the problem and its urgency. Once you finished, make sure your ticket is filled out completely and correct and then
    click submit ticket to submit the ticket to the system.
    To update any tickets in the system, simply click create update to update a ticket. Here input your name and select the ticket ID you want to update
    Then provide a description of the update to the ticket. In the case that the problem associated with the ticket is resolved, simply click "Problem has been resolved?"
    Finally click "Update Ticket" to input the update to the system. In the case that you selected <q>Problem has been resolved?</q>, the ticket will automatically be deleted
    from the system. In the tickets tab you will have any overview of all the tickets in the system and all of their attributes. If you want to delete a ticket here, click
    <q>Delete Ticket</q> to go to the delete a ticket page.  Here you can input your name and the associated ticket Id you want to delete. Please provide a description as to why
    you are deleting the ticket and the option to select whether the problem has been resolved. Only administrator users can delete tickets for everyone, so if you cannot delete a
    ticket assigned to someone else, only the assigned person can. Talk to your administrator about any concerns for deleting a ticket.
  </p>
  <img src="{% static 'bugs/images/palmtechLogoSmall.png' %}" style="position:relative;left:580px;">
</div1>
{% endblock %}

bugs/templates/bugs/base.html
{% load static %}

<!-- Antonio: Design of front end system. Design of UI and website structure and links. User login and user regstration system.-->
<!-- Design of forms and templates for front end.-->
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>BugTracker</title>
	<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'fa/css/fontawesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'fa/css/solid.min.css' %}">
	<link rel="icon" href= "{% static 'bugs/images/palmtechLogoSmall.png' %}">
	<style>
		#logo {
		}
		#total-orders {
			background-image: linear-gradient(135deg, #81FBB8 10%, #28C76F 100%);
		}
		#orders-delivered {
			background-color: #0093E9;
			background-image: linear-gradient(160deg, #0093E9 0%, #80D0C7 100%);
		}
		#orders-pending {
			background-color: #FBAB7E;
			background-image: linear-gradient(62deg, #FBAB7E 0%, #F7CE68 100%);
		}
		body {
			min-height: 100vh;
			width: 100%;
			background: linear-gradient(rgba(0,0,0,0.25) 100%, rgba(0,0,0,0.25) 100%), url("/static/bugs/images/background.png");
			background-position: center;
			background-size: cover;
			position: relative;
		}
		#logo1 {
			padding-left: 620px;
			padding-top: 0px;
		}
		.intro {
			color: white;
			text-align: center;
			position: absolute;
		}
		.intro h2 {
			color: white;
			text-align: center;
			padding: 20px;
			font-size: 60px;
		}
		.intro p1 {
			color: white;
			margin: 10px 0 40px;
			font-size: 16px
		}
		.learnbutton {
			display: inline-block;
			color: white;
			border: 1px solid white;
			background: transparent;
			padding: 12px 34px;
			font-size: 14px;
			position: relative;
			cursor: pointer;
		}
		.loginbutton {
			display: inline-block;
			color: white;
			border: 1px solid white;
			background: transparent;
			padding: 12px 34px;
			font-size: 14px;
			position: relative;
			cursor: pointer;
		}
    .centered {
      margin: auto;
      padding: 15px;
      width: 100%;
    }
    form label {
        padding-right: 8px;
    }
		footer {
			position: absolute;
			bottom: 16px;
			left: 48px;
			color: #fff;
		}
	</style>
</head>
<body>
	{% include "bugs/navbar.html" %}
	<div class="container-fluid">
		<div style="width:100%;height:120px"></div>
		{% if messages %}
		<div class="row">
			{% for message in messages %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
				{{message}}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{% endfor %}
		</div>
		{% endif %}
		{% block content %}
		{% endblock %}
		<div style="width:100%;height:100px"></div>
	</div>
	<footer>
		<center>
			<p><a href="#" class="text-warning">Privacy Policy</a> &verbar; &copy; 2022 Palm Technologies, LLC.</p>
		</center>
	</footer>
	<script src="{% static 'jquery-3.4.1.slim.min.js' %}" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="{% static 'popper.min.js' %}" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="{% static 'bootstrap.min.js' %}" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

bugs/templates/bugs/create_ticket.html
{% extends 'bugs/base.html' %}
{% block content %}
<style>#cat_results{display:none;width:350px;position:absolute;box-shadow: 0px 24px 16px -12px rgba(0, 0, 0, 0.5);}</style>
<script>
  var xhr = new XMLHttpRequest();
  xhr.addEventListener("readystatechange", function() {
    if (this.readyState === this.DONE) {
      $("#cat_results").empty();
      var s = this.responseText.split(",");
      for (var i = 0; i < s.length; i++) {
        $("#cat_results").append("<option>" + s[i].trim() + "</option>");
      }
    }
  });

  setTimeout(function() {
    var offset = $('#id_category').offset();
    $('#cat_results').css({
      "top": Math.round(offset.top) + 36,
      "left": Math.round(offset.left)
    });

    $("#id_category").on("focus click", function() {
      $("#cat-results").show();
    });
    $("#cat_results").on("blur", function() {
      $("#cat_results").hide();
    });

    $("#id_category").on("change keyup", function() {
      $("#cat_results").show();
      $("#cat_results").empty();
      xhr.open("GET", "/search_categories/" + $(this).val());
      xhr.send(null);
    });

    $("#cat_results").on("change", function() {
      $("#id_category").val($(this).val());
    });
  }, 1000);
</script>

<select class="custom-select" id="cat_results" multiple></select>

<div class="row text-white" style="width:100%;padding-top:20px">
  <div style="margin-left:auto;margin-right:auto;width:100%;text-align:center;">
    <h2>Create Ticket</h2>
</div>

<div class="row centered text-white" style="max-width: 500px">
    <form action="/submit_ticket" method="GET">
        {% csrf_token %}
        <table>
        {{form}}
        <tr><td><hr></td><td><hr></td></tr>
        <tr><td></td><td><button type="submit" class="btn btn-primary btn-block">Submit</button></td></tr>
        </table>
    </form>
</div>

{% endblock %}

bugs/templates/bugs/create_update.html
{% extends 'bugs/base.html' %}
{% block content %}

<div class="row text-white" style="width:100%;padding-top:20px">
  <div style="margin-left:auto;margin-right:auto;width:100%;text-align:center;">
    <h2>Create Ticket</h2>
</div>

<div class="row centered text-white" style="max-width: 500px">
    <form action="/submit_update" method="GET">
        {% csrf_token %}
        <table>
        {{form}}
        <tr><td><hr></td><td><hr></td></tr>
        <tr><td></td><td><button type="submit" class="btn btn-primary btn-block">Submit</button></td></tr>
        </table>
    </form>
</div>

{% endblock %}

bugs/templates/bugs/dashboard.html
{% extends 'bugs/base.html' %}
{% block content %}
{% load bugs_tags %}
<!--User dashboard-->
<script>document.title="Dashboard - BugTracker";</script>
<style>
	/*#recent {
		background-color: #89d4cf;
		background-image: linear-gradient(315deg, #89d4cf 0%, #6e45e1 74%);
		padding-left: 240px;
	}
	.buttondash {
		background-color: #000000;
		background-image: linear-gradient(147deg, #000000 0%, #04619f 74%);
		color: white;
		border: none;
		font-weight: bold;
	}
	#ticketAssigned {
		background-color: #89d4cf;
		background-image: linear-gradient(315deg, #89d4cf 0%, #6e45e1 74%);
	}
	#ticketSubmit {
		background-color: #89d4cf;
		background-image: linear-gradient(315deg, #89d4cf 0%, #6e45e1 74%);
	} */
</style>

{% include 'bugs/status.html' %}

<div class="row" style="padding-top:36px">
	<div class="col">
		<div class="card">
			<div class="card-header">
				<h5 id="ticketAssigned"><i class="fas fa-ticket-alt"></i>&nbsp;My Assigned Tickets</h5>
			</div>
			<div class="card-body">
				<a class="btn btn-success btn-md btn-block buttondash" href="/createTicket"><i class="fas fa-plus"></i>&nbsp;Create Ticket</a>
				<table class="table table-sm">
					<tr>
						<th>ID</th>
						<th>Title</th>
						<th>Date Created</th>
						<th>Category</th>
						<th>Status</th>
						<th>Urgency</th>
						<th>Created By</th>
						<th>Assigned To</th>
					</tr>
					{% for ticket in assignTickets %}
						<tr>
							<td><a href="/ticket/details/{{ticket.ticketId}}">{{ticket.ticketId}}</a></td>
							<td><a href="/ticket/details/{{ticket.ticketId}}">{{ticket.title}}</a></td>
							<td><a href="/ticket/details/{{ticket.ticketId}}">{{ticket.timestamp}}</a></td>
							<td><a href="/ticket/details/{{ticket.ticketId}}">{{ticket.category}}</a></td>
							<td><a href="/ticket/details/{{ticket.ticketId}}">{{ticket.status}}</a></td>
							<td><a href="/ticket/details/{{ticket.ticketId}}" class="text-{{ticket.urgency|toBS}}">{{ticket.urgency}}</a></td>
							<td><a href="/ticket/details/{{ticket.ticketId}}">{{ticket.createdBy}}</a></td>
							<td><a href="/ticket/details/{{ticket.ticketId}}">{{ticket.assignedTo}}</a></td>
						</tr>
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
</div>

<!-- <div class="row" style="padding-top:48px">
	<div class="col">
		<div class="card">
			<div class="card-header">
				<h5 id="recent"><i class="fas fa-history"></i>&nbsp;Updates</h5>
			</div>
			<div class="card-body">
				<a class="btn btn-success btn-md btn-block buttondash" href="/createUpdate"><i class="fas fa-plus"></i>&nbsp;Create Update</a>
        <table class="table table-sm">
					<tr>
						<th>ID</th>
						<th>Ticket</th>
						<th>Employee</th>
					</tr>
					{% for update in updates %}
					<tr>
						<td><a href="/update/details/{{update.updateId}}">{{update.updateId}}</a></td>
						<td><a href="/update/details/{{update.updateId}}">{{update.onTicket}}</a></td>
						<td><a href="/update/details/{{update.updateId}}">{{update.madeBy}}</a></td>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
</div> -->
{% endblock %}

bugs/templates/bugs/homePage.html
{% extends 'bugs/main.html' %}
{% load static %}
{% block content %}
<html>
<body>

    <div>
        <section class="header1">
            <h3 id="logo1">
                <a href="/main">
                    <img src="{% static 'bugs/images/palmtechLogoSmall.png' %}"
                         width="400"
                         height="400">
                </a>
            </h3>
            <div class="intro">
                <h2>Welcome to Bug Tracker developed by Palm Technologies</h2>

                <p1>
                    Our team at Palm Technlogies is excited to introduce our new BugTracker software that will allow
                    you and your team of engineers to keep track of bugs in your engineering projects. Simple and easy to use,
                    BugTracker allows you to simply create a ticket of your bug and assign it to a member of your team to keep track of.<br>
                    <br><br><br>
                </p1>
                <a href="\about" class="learnbutton"> Learn More </a>
                <br><br>
                <a href="{% url 'dashboard' %}" class="loginbutton"> Go to User Dashboard </a>

            </div>


        </section>
        {% endblock %}
    </div>


</body>

</html>